version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 509399625426.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t springboot-app .
      - docker tag springboot-app:latest 509399625426.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/springboot-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 509399625426.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/springboot-app:latest

artifacts:
  files: []
